version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - ENV=dev
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend  # Dockerfile 사용하도록 설정
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules  # node_modules는 볼륨 제외
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
