// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4SWmLChNCXaLuZnDt9Byj4
import * as React from "react";
import { CmsCredentialsProvider } from "@plasmicpkgs/plasmic-cms";

export default function GlobalContextsProvider(props) {
  const { children, cmsCredentialsProviderProps } = props;
  return (
    <CmsCredentialsProvider
      {...cmsCredentialsProviderProps}
      databaseId={
        cmsCredentialsProviderProps &&
        "databaseId" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseId
          : "mn6EnZwwEFGhFFawwZYobS"
      }
      databaseToken={
        cmsCredentialsProviderProps &&
        "databaseToken" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.databaseToken
          : "5EkFsYr7vTg3R7bEjuQfEjdiKyKgu40AYsPbqDwc7QxW3k3aVK0BaUCr8nw5OnxXGSqjFCA67NSuUc5kIYpw"
      }
      host={
        cmsCredentialsProviderProps && "host" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.host
          : "https://data.plasmic.app"
      }
      locale={
        cmsCredentialsProviderProps && "locale" in cmsCredentialsProviderProps
          ? cmsCredentialsProviderProps.locale
          : undefined
      }
    >
      {children}
    </CmsCredentialsProvider>
  );
}
